project/circles/urls.py
from django.urls import path

from .views import (
    CircleCreateView,
    CircleDetailView,
    CircleListView,
    CircleUpdateView,
    CompanionDeleteView,
    JoinRequestUpdateView,
    join_as_companion,
)

urlpatterns = [
    path("", CircleListView.as_view(), name="circle-list"),
    path(
        "create",
        CircleCreateView.as_view(),
        name="circle-create",
    ),
    path("<slug:pk>/update/", CircleUpdateView.as_view(), name="circle-update"),
    path("<slug:circle_id>/join/", join_as_companion, name="circle-join"),
    path("<slug:pk>/", CircleDetailView.as_view(), name="circle-detail"),
    path(
        "<slug:circle_id>/join-request/<slug:join_request_id>",
        JoinRequestUpdateView.as_view(),
        name="update-join-request",
    ),
    path(
        "<slug:circle_id>/companion/<pk>/delete",
        CompanionDeleteView.as_view(),
        name="delete-companion",
    ),
]

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

media_urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api_urlpatterns = [
    path(
        "accounts/registration/",
        include("dj_rest_auth.registration.urls"),
    ),
    path(
        "accounts/",
        include("dj_rest_auth.urls"),
    ),
]

urlpatterns = [
    path("api/v1/", include(api_urlpatterns)),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
    path("caregivers/", include("caregivers.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("circles/", include("circles.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + media_urlpatterns

handler404 = "error_handling.views.handler404"
handler500 = "error_handling.views.handler500"
handler403 = "error_handling.views.handler403"
handler400 = "error_handling.views.handler400"

project/activities/models.py
import datetime
from enum import Enum

from circles.models import Circle
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Activity(models.Model):
    class ActivityTypeIcons(Enum):
        APPOINTMENT = "bi-calendar-event"
        CALL = "bi-camera-video"
        ENTERTAINMENT = "bi-ticket-perforated"
        ERRAND = "bi-building"
        HOUSEWORK = "bi-house"
        NATURE = "bi-tree"
        OUTING = "bi-cup-straw"
        SHOPPING = "bi-cart"

    class ActivityTypeChoices(models.TextChoices):
        APPOINTMENT = "APPOINTMENT", _("Appointment")
        CALL = "CALL", _("Call")
        ENTERTAINMENT = "ENTERTAINMENT", _("Entertainment")
        ERRAND = "ERRAND", _("Errand")
        HOUSEWORK = "HOUSEWORK", _("Housework")
        NATURE = "NATURE", _("Nature")
        OUTING = "OUTING", _("Outing")
        SHOPPING = "SHOPPING", _("Shopping")

    activity_type = models.CharField(
        max_length=15,
        choices=ActivityTypeChoices.choices,
        default=ActivityTypeChoices.APPOINTMENT,
    )

    activity_date = models.DateField(default=datetime.date.today)

    note = models.CharField(
        max_length=50,
        help_text=_(
            "Optionally, add a brief note. For privacy, avoid adding sensitive information."  # noqa: E501
        ),
        null=True,
        blank=True,
    )

    circle = models.ForeignKey(
        to=Circle,
        related_name="activities",
        on_delete=models.CASCADE,
        null=True,
    )

    participants = models.ManyToManyField(User, related_name="activities")

    done = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("activity")
        verbose_name_plural = _("activities")
        ordering = [
            "activity_date",
        ]

    def __str__(self):
        return self.get_activity_type_display()

    def get_absolute_url(self):
        return reverse("activity-detail", kwargs={"pk": self.pk})

    @property
    def icon(self):
        return self.ActivityTypeIcons[self.activity_type].value

    @property
    def remaining_eligible_companions(self):
        """Return a QuerySet of the circle's companions who are not already activity participants."""  # noqa: E501
        # Only care group members are eligible to participate
        companions = self.circle.companions

        # Get current activity participants
        current_participants = self.participants.all()

        # Exclude existing companions from care group members
        remaining_eligible_companions = companions.difference(current_participants)

        return remaining_eligible_companions

project/circles/models.py
import uuid
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from easy_thumbnails.fields import ThumbnailerImageField

User = get_user_model()


class Circle(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    photo = ThumbnailerImageField(upload_to="circle_photos", blank=True)

    class Meta:
        verbose_name_plural = _("circles")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("circle-detail", kwargs={"pk": self.pk})

    @property
    def companions(self):
        """Return a list of users who are companions for this circle."""
        companions = User.objects.filter(companions_through__circle=self)

        return companions

    @property
    def organizers(self):
        """Return a list of users who are care organizers for this circle."""
        organizers = User.objects.filter(
            companions_through__circle=self,
            companions_through__is_organizer=True,
        )

        return organizers

    @property
    def upcoming_activities(self):
        """Return a list of activities that happen today or later."""
        today = datetime.today()

        return self.activities.filter(activity_date__gte=today)

    @property
    def annotated_companions(self):
        """
        Return a companion list annotated with activity count for current persion.

        TODO: refactor for performance,
            such as by adding a cached "activity_count" property to Companion model
        """
        annotated_companions = []

        for member in self.companions_through.all():
            member.activity_count = member.get_activity_count(circle=self)

            annotated_companions.append(member)

        return annotated_companions

    @property
    def companionship_score(self):
        """
        Companionship score is the number of times companions have
        participated in care group activities.
        E.g., if a care group has ten activities and each activity
        has had two participants, the companionship score
        will be 20.

        Thanks goes to Marcel from StackOverflow
        https://stackoverflow.com/a/70592240/1191545
        """

        return User.objects.filter(activities__circle=self).count()

    @property
    def pending_join_requests(self):
        """Get join requests who have not been approved or rejected."""
        return self.join_requests.filter(status="PENDING")


class Companion(models.Model):
    circle = models.ForeignKey(
        to=Circle, related_name="companions_through", on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        to=User, related_name="companions_through", on_delete=models.CASCADE
    )
    is_organizer = models.BooleanField(default=False)

    def __str__(self):
        return self.user.display_name

    def get_activity_count(self, circle=None):
        """Return a count of activities between the related user and circle."""
        return self.user.get_activity_count(circle=self.circle)

    class Meta:
        unique_together = (
            "circle",
            "user",
        )


class JoinRequest(models.Model):
    """Request to join circle as a companion."""

    class JoinRequestStatusChoices(models.TextChoices):
        PENDING = "PENDING", _("Pending")
        APPROVED = "APPROVED", _("Approved")
        REJECTED = "REJECTED", _("Rejected")

    circle = models.ForeignKey(
        to=Circle, related_name="join_requests", on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        to=User, related_name="join_requests", on_delete=models.CASCADE
    )
    status = models.CharField(
        max_length=15,
        choices=JoinRequestStatusChoices.choices,
        default=JoinRequestStatusChoices.PENDING,
    )

project/circles/views.py
from activities.forms import ActivityModelForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Circle, Companion, JoinRequest


class CompanionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Companion
    context_object_name = "companion"

    def get_success_url(self):
        return reverse("circle-detail", kwargs={"pk": self.object.circle.id})

    def test_func(self):
        """
        Only care organizer can remove companions for the related circle

        Also, make sure the Circle ID in the URL path matches the
        Circle ID from the Companion object.This is to encourage
        that the requesting user knows the correct Circle ID,
        since Companion PKs are sequential.
        """
        request_circle_id = self.kwargs["circle_id"]

        companion = self.get_object()

        circle = companion.circle

        user = self.request.user

        # Tests
        # TODO: determine if there is a more idiomatic way
        # to validate the request circle_id
        user_can_remove_companion = user in circle.organizers
        request_circle_id_matches_circle_id = request_circle_id == str(circle.id)

        return user_can_remove_companion and request_circle_id_matches_circle_id


class CircleCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Circle
    fields = [
        "name",
        "photo",
    ]

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields["name"].widget.attrs.update({"autofocus": "autofocus"})

        return form

    def form_valid(self, form):
        # Save circle
        # so we can add request user as coordinator
        circle = form.save()

        # Add user who creates a circle as organizer
        companion = Companion(
            circle=circle,
            user=self.request.user,
            is_organizer=True,
        )

        companion.save()

        return HttpResponseRedirect(circle.get_absolute_url())

    def test_func(self) -> bool:
        """
        For now, users can only create at most one Circle (a.k.a. care circle)

        The limit is intended to reduce the liklihood of abuse while eventually
        encouraging users to become supporters when that tier becomes available.

        Here, we check whether a user is already a care circle organizer. If so,
        they cannot add a new Circle (care circle).
        """

        return not self.request.user.is_care_circle_organizer


# First, ensure user is logged in, then make sure they pass test (are a companion)
class CircleDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Circle
    context_object_name = "circle"
    template_name = "circles/circle_detail.html"

    def test_func(self, *args, **kwargs):
        """Only companions (and organizers) can access the circle detail view"""
        circle = Circle.objects.get(id=self.kwargs["pk"])
        user = self.request.user

        # Check whether user is circle's companion
        user_can_access_circle = user in circle.companions

        return user_can_access_circle

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.object.activities.all()
        paginator = Paginator(queryset, 4)
        page = self.request.GET.get("page")

        """
        {{ request.get_host }}{% url 'circle-join' circle.id %}
        """

        # Create companion invitation URL
        circle_id = context["circle"].id
        invitation_path = reverse("circle-join", kwargs={"circle_id": circle_id})
        invitation_url = self.request.build_absolute_uri(invitation_path)

        context["invitation_url"] = invitation_url

        context["add_activity_form"] = ActivityModelForm

        try:
            activities_page = paginator.page(page)
        except PageNotAnInteger:
            activities_page = paginator.page(1)
        except EmptyPage:
            activities_page = paginator.page(paginator.num_pages)

        context["activity_page"] = activities_page

        return context


class CircleListView(LoginRequiredMixin, TemplateView):
    template_name = "circles/circle_list.html"


# First, ensure user is logged in, then make sure they pass test (are an organizer)
class CircleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Circle
    fields = [
        "name",
        "photo",
    ]

    def test_func(self, *args, **kwargs):
        """Only organizers can update the circle's details"""
        circle = Circle.objects.get(id=self.kwargs["pk"])
        user = self.request.user

        # Check whether user is circle's care organizer
        user_can_update_circle = user in circle.organizers

        return user_can_update_circle

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields["name"].widget.attrs.update({"autofocus": "autofocus"})

        return form

    def form_valid(self, form):
        """Used to delete old photos and thumbnails"""
        circle = Circle.objects.get(id=self.kwargs["pk"])
        circle.photo.delete()

        circle = form.save()

        return HttpResponseRedirect(circle.get_absolute_url())


def join_as_companion(request, circle_id):
    if request.user.is_authenticated:
        # Ensure circle exists
        try:
            circle = Circle.objects.get(pk=circle_id)
        except Circle.DoesNotExist:
            message = _("Could not find circle at the requested URL")
            raise Http404(message)

        # Redirect to circle page if user is already a companion
        if Companion.objects.filter(
            circle=circle_id,
            user=request.user,
        ).exists():
            return redirect(circle)

        # Show "request received" if user has already submitted a join request
        if JoinRequest.objects.filter(
            circle=circle_id,
            user=request.user,
        ).exists():
            return render(request, "circles/circle_join_received.html")

        # Handle join request
        if request.method == "POST":
            join_request = JoinRequest(
                circle=circle,
                user=request.user,
            )

            join_request.save()

            return render(request, "circles/circle_join_received.html")

        # Show join form by default
        return render(request, "circles/circle_join.html")
    # Show login/register buttons by default
    return render(request, "circles/login_register.html")


class JoinRequestUpdateView(View):
    def get(self, request, circle_id, join_request_id, *args, **kwargs):
        circle = Circle.objects.get(id=circle_id)

        # Only organizer can update join requests
        if request.user not in circle.organizers:
            raise PermissionDenied()
        else:
            join_request = JoinRequest.objects.get(id=join_request_id, circle=circle)

            join_request_status = request.GET["status"]

            # If approved, add join request user as companion to circle
            if join_request_status == "APPROVED":
                companion = Companion(
                    circle=circle,
                    user=join_request.user,
                )
                companion.save()

            # Always delete the join request once it has been handled by the organizer
            join_request.delete()

            return redirect(circle)

project/circles/templates/circles/circle_activity.html
{% load i18n %}
{% load crispy_forms_tags %}

<div class="card mb-2">
    <div class="card-body">
        <div class="row">
            <div class="col-1 fs-3 d-flex flex-column">
                <i class="{{ activity.icon }}"></i>
            </div>
            <div class="col">
                <p class="card-title mt-1 mb-0">{{ activity }}</p>
                <p class="text-muted mb-0">{{ activity.activity_date }}</p>
                {% if activity.note %}
                    <p class="text-muted mb-0">
                        {{ activity.note }}
                    </p>
                {% endif %}

                <!-- organizer can add other eligible companions -->
                {% if user in circle.organizers %}
                    {% if activity.remaining_eligible_companions %}
                        <button
                            type="button"
                            title="{% translate 'Add' %}"
                            style="border: none;"
                            class="badge rounded-pill bg-default text-dark"
                            data-bs-toggle="modal"
                            data-bs-target="#add-activity-participant-modal-{{ activity.id }}"
                        >
                            <i class="bi bi-person"></i>
                            {% translate 'Add' %}
                            <i class="bi bi-plus-lg"></i>
                        </button>
                    {% endif %}
                {% endif %}

                {% if user not in activity.participants.all %}
                    <form action="{% url 'activity-add-participant' activity.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        <button
                            type="submit"
                            title="{% translate 'Participate' %}"
                            style="border: none;"
                            class="badge rounded-pill bg-success"
                        >
                            <i class="bi bi-person"></i>
                            {% translate 'Join' %}
                            <i class="bi bi-plus-lg"></i>
                        </button>
                    </form>
                {% endif %}

                {% if activity.participants.count %}
                    {% for participant in activity.participants.all %}
                        {% if user in circle.organizers %}
                            <!-- group organizers can remove other participants -->
                            <form action="{% url 'activity-remove-participant' activity.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{ participant.id }}">
                                <button
                                    type="submit"
                                    title="{% translate 'Remove participant' %}"
                                    style="border: none;"
                                    class="badge rounded-pill bg-primary">
                                    <i class="bi bi-person"></i>
                                    {{ participant.display_name }}
                                    <i class="bi bi-x-lg"></i>
                                </button>
                            </form>
                        {% elif participant.id == user.id %}
                            <!-- participant can remove self -->
                            <form action="{% url 'activity-remove-participant' activity.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{ user.id }}">
                                <button
                                    type="submit"
                                    title="{% translate 'Remove participant' %}"
                                    style="border: none;"
                                    class="badge rounded-pill bg-primary">
                                    <i class="bi bi-person"></i>
                                    {{ participant.display_name }}
                                    <i class="bi bi-x-lg"></i>
                                </button>
                            </form>
                        {% else %}
                            <!-- display participant without remove button by default -->
                            <span class="badge rounded-pill bg-primary">
                                <i class="bi bi-person"></i>
                                {{ participant.display_name }}
                            </span>
                        {% endif %}

                    {% endfor %}
                {% else %}
                    <span class="badge rounded-pill bg-warning text-dark">{% translate "No participants" %}</span>
                {% endif %}
            </div>

            <div class="col-1 pr-0 d-flex flex-column align-items-end justify-content-between">
                <div class="btn-group">
                    <button
                        type="button"
                        class="btn btn-outline-secondary btn-sm rounded-circle"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                        title="{% translate 'Actions' %}"
                    >
                        <i class="bi bi-three-dots"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <button
                                type="button"
                                title="{% translate 'Edit activity' %}"
                                class="dropdown-item"
                                data-bs-toggle="modal"
                                data-bs-target="#edit-activity-modal-{{ activity.id }}">
                                <i class="bi bi-pencil"></i>
                                {% translate 'Edit activity' %}
                            </button>
                            {% if user in circle.organizers %}
                                <button
                                    type="button"
                                    title="{% translate 'Delete activity' %}"
                                    class="dropdown-item"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete-activity-confirmation-modal-{{ activity.id }}">
                                    <i class="bi bi-calendar-x"></i>
                                    {% translate 'Delete activity' %}
                                </button>
                            {% endif %}
                        </li>
                    </ul>
                </div>

                {% if not activity.done %}
                    <a
                        type="button"
                        href="{% url 'activity-set-done' activity.id %}"
                        title="{% translate 'Mark activity as complete' %}"
                        class="btn btn-sm btn-success rounded-circle">
                        <i class="bi bi-check-lg"></i>
                    </a>
                {% else %}
                    {% translate "Done" %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Edit activity modal -->
<div class="modal fade" id="edit-activity-modal-{{ activity.id }}" tabindex="-1" aria-labelledby="edit-activity-modal-label-{{ activity.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="edit-activity-modal-label-{{ activity.id }}">
                    {% translate "Edit activity" %}
                </h5>

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'activity-update' activity.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="circle" value="{{ circle.id }}">


                    {{ add_activity_form.activity_type.label_tag }}
                    <select class="form-select mb-2" aria-label='{% translate "Activity type select" %}' name="activity_type">
                        {% for value, text in form.activity_type.field.choices %}
                            <option value="{{ value }}"
                                {% if activity.activity_type == value %}selected="selected"{% endif %}>
                                {{ text }}
                            </option>
                        {% endfor %}
                    </select>

                    {{ add_activity_form.activity_date.label_tag }}
                    <input
                        type="text"
                        name="activity_date"
                        value="{{ activity.activity_date | date:'c' }}"
                        class="dateinput form-control mb-2"
                        required=""
                        id="id_activity_date">

                    {{ add_activity_form.note.label_tag }}
                    <input
                        type="text"
                        name="note"
                        {% if activity.note %}
                            {% comment %}Prevent empty activity note from displaying as None{% endcomment %}
                            value="{{ activity.note }}"
                        {% endif %}
                        class="form-control mb-2"
                        id="id_note">
                    <p id="hint_id_note" class="form-text text-muted mx-2">
                        {{ add_activity_form.note.help_text | safe }}
                    </p>

                    <button type="submit" class="btn btn-success ml-auto">
                        {% translate "Save" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Add activity participant modal -->
<div class="modal fade" id="add-activity-participant-modal-{{ activity.id }}" tabindex="-1" aria-labelledby="add-activity-participant-modal-label-{{ activity.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="add-activity-participant-modal-label-{{ activity.id }}">
                    {% translate "Add participant" %}
                </h5>

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'activity-add-participant' activity.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <select class="form-select mb-2" aria-label='{% translate "Participant select" %}' name="user_id">
                        {% for companion in activity.remaining_eligible_companions %}
                            <option value="{{ companion.id }}">
                                {{ companion.display_name }}
                            </option>
                        {% endfor %}
                    </select>

                    <button type="submit" class="btn btn-success ml-auto">
                        {% translate "Save" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete activity confirmation modal -->
<div class="modal fade" id="delete-activity-confirmation-modal-{{ activity.id }}" tabindex="-1" aria-labelledby="delete-activity-participant-modal-label-{{ activity.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title h5" id="delete-activity-participant-modal-label-{{ activity.id }}">
                    <i class="bi bi-calendar-x"></i>
                    {% translate "Delete activity" %}
                </p>

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
            </div>
            <div class="modal-body">
                <p>
                    {% translate "Are you sure you want to delete this activity?" %}
                </p>

                <form action="{% url 'activity-delete' activity.id %}" method="post">{% csrf_token %}
                    <button type="submit" class="btn btn-danger ml-auto">
                        {% translate "Delete" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

project/circles/templates/circles/circle_add_activity_modal.html
{% load crispy_forms_tags %}
{% load i18n %}

<!-- Add Activity modal -->
<div class="modal fade" id="add-activity-modal" tabindex="-1" aria-labelledby="add-activity-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="add-activity-modal-label">
                    {% translate "Add activity" %}
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'activity-create' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="circle" value="{{ circle.id }}">
                    {{ add_activity_form.activity_type|as_crispy_field }}
                    {{ add_activity_form.activity_date|as_crispy_field }}
                    {{ add_activity_form.note|as_crispy_field }}
                    <button type="submit" class="btn btn-success ml-auto">{% translate "Submit" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

project/circles/templates/circles/circle_join.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <h1>
        {% translate "Join as companion" %}
    </h1>

    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">
            {% translate "Request to join as companion" %}
        </button>
        <a href="/" class="btn btn-outline-danger">
            {% translate "Cancel" %}
        </a>
    </form>
{% endblock content %}